services:
  - type: web
    name: edictum-console
    runtime: docker
    region: frankfurt
    plan: starter
    branch: master
    healthCheckPath: /api/v1/health
    envVars:
      - key: EDICTUM_DATABASE_URL
        sync: false
      - key: EDICTUM_REDIS_URL
        sync: false
      - key: EDICTUM_SECRET_KEY
        sync: false
      - key: EDICTUM_SIGNING_KEY_SECRET
        sync: false
      - key: EDICTUM_ADMIN_EMAIL
        sync: false
      - key: EDICTUM_ADMIN_PASSWORD
        sync: false
      - key: EDICTUM_BASE_URL
        sync: false
      - key: EDICTUM_CORS_ORIGINS
        sync: false
      - key: EDICTUM_ENV_NAME
        value: production
